apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-presistent-volume
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"